pipeline {
    agent any

    environment {
        PATH = "$PATH:/opt/usr/share/maven/bin"
    }

    stages {
        stage('Get Code') {
            steps {
                git 'https://github.com/PradeepReddyGunna/Java.war-app.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh 'mvn sonar:sonar'
                }
            }
        }
    }
}
